version: '3'

services:
  dbmysql:
    build: ./db
    environment:
      MYSQL_DATABASE: cart
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
  containers-1:
    build: ./containers/mem
    depends_on:
      dbmysql:
        condition: service_healthy
      memcached:
        condition: service_started
    ports:
      - "8090:8090"
  containers-2:
    build: ./containers/mem
    depends_on:
      dbmysql:
        condition: service_healthy
      memcached:
        condition: service_started
    ports:
      - "8091:8090"
  containers-3:
    build: ./containers/mem
    depends_on:
      dbmysql:
        condition: service_healthy
      memcached:
        condition: service_started
    ports:
      - "8092:8090"
  containers-4:
    build: ./containers/loc
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "8093:8090"
  containers-5:
    build: ./containers/loc
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "8094:8090"
  containers-6:
    build: ./containers/loc
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "8095:8090"
  memcached:
    container_name: cache
    image: memcached:1.6.16

    ports:
      - "11211:11211"
  lb:
    build: ./lb
    depends_on:
      containers-1:
        condition: service_started
      containers-2:
        condition: service_started
      containers-3:
        condition: service_started
      containers-4:
        condition: service_started
      containers-5:
        condition: service_started
      containers-6:
        condition: service_started
    ports:
      - "80:80"